db:
  image: postgres:9.4.4
  ports:
    - "5432"
  volumes:
    - ./docker/volumes/postgres:/var/lib/postgresql/data

web:
  build: .
  volumes:
    - .:/wannatalk.io
  links:
    - db
  ports:
    - "5001:3000"
  command: bundle exec rails s -b 0.0.0.0
