# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec01454be7d44754aac180912182c92dbbb3465722f6a81edf4cca548a65707abd394e413807f395de5607a3bee44777f824ed3c66c846a3df381a10a149120b

test:
  secret_key_base: 1c103abe7d8b2d7558c78e89f0fca98f45be0308fd3d544c49fc3a6d4324a97ca8ccd52d2fe0db1dda6f4cafb0e7f56683ecb71a121966756a44afab9b93b000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
